select	
	
	TO_CHAR(SQ_XLA_AE_LINES_HEADER.CODE_COMB_ID_AEHL)	   C1_GL_ACCOUNT_ID,
	TO_CHAR(SQ_XLA_AE_LINES_HEADER.LEDGER_ID_AEHL)	   C2_LEDGER_ID,
	null	   C3_CUSTOMER_ID,
	CASE WHEN SQ_XLA_AE_LINES_HEADER.PARTY_TYPE_CODE_AEHL = 'C' THEN TO_CHAR(SQ_XLA_AE_LINES_HEADER.PARTY_ID_AEHL) ELSE COALESCE(TO_CHAR(SQ_XLA_CST.SOLD_TO_ORG_ID),TO_CHAR(SQ_XLA_OZF_CLAIM_SETTLEMENTS.CUST_ACCOUNT_ID),TO_CHAR(SQ_XLA_OZF_ACCRUALS.CUST_ACCOUNT_ID)) END	   C4_CUSTOMER_ACCT_ID,
	CASE WHEN SQ_XLA_AE_LINES_HEADER.PARTY_TYPE_CODE_AEHL  = 'S' THEN TO_CHAR(SQ_XLA_AE_LINES_HEADER.PARTY_ID_AEHL) ELSE NULL END	   C5_SUPPLIER_ID,
	CASE WHEN SQ_XLA_AE_LINES_HEADER.PARTY_TYPE_CODE_AEHL = 'S' THEN TO_CHAR(SQ_XLA_AE_LINES_HEADER.PARTY_SITE_ID_AEHL) ELSE NULL END	   C6_SUPPLIER_ACCT_ID,
	CASE WHEN SQ_XLA_TRANSACTION_ENTITIES.APPLICATION_ID = 222 THEN TO_CHAR(SQ_XLA_TRANSACTION_ENTITIES.SECURITY_ID_INT_1) ELSE NULL END	   C7_RECEIVABLES_ORG_ID,
	CASE WHEN SQ_XLA_TRANSACTION_ENTITIES.APPLICATION_ID = 200 THEN TO_CHAR(SQ_XLA_TRANSACTION_ENTITIES.SECURITY_ID_INT_1) ELSE NULL END	   C8_PAYABLES_ORG_ID,
	SQ_XLA_AE_LINES_HEADER.PERIOD_SET_NAME_GL || '~' || SQ_XLA_AE_LINES_HEADER.PERIOD_NAME_AEHL	   C9_PERIOD_ID,
	'GL_JOURNAL_SOURCE~'|| SQ_XLA_AE_LINES_HEADER.JE_SOURCE_NAME_DL	   C10_JOURNAL_SOURCE_ID,
	SQ_XLA_AE_LINES_HEADER.APPLICATION_SHORT_NAME_FND	   C11_ACCOUNTING_SOURCE,
	SQ_XLA_AE_LINES_HEADER.ACCOUNTING_DATE_AEHL	   C12_ACCOUNTING_DT,
	SQ_XLA_AE_LINES_HEADER.GL_TRANF_DATE_AEHL	   C13_GL_TRANSFER_DT,
	SQ_XLA_AE_LINES_HEADER.DISPLAYED_LINE_NUMBER	   C14_JOURNAL_LINE_NUM,
	SQ_XLA_AE_LINES_HEADER.ACCT_CLASS_CD_AEHL	   C15_ACCOUNTING_CLASS_CODE,
	SQ_XLA_AE_LINES_HEADER.JE_CATGRY_NAME_AEHL	   C16_JOURNAL_CATEGORY,
	SQ_XLA_AE_LINES_HEADER.EVENT_CLASS_CODE_DL	   C17_EVENT_CLASS_CODE,
	SQ_XLA_AE_LINES_HEADER.EVENT_TYPE_CODE_DL	   C18_EVENT_TYPE_CODE,
	SQ_XLA_AE_LINES_HEADER.AE_HDR_DESC_AEHL	   C19_JOURNAL_HEADER_DESCR,
	SQ_XLA_AE_LINES_HEADER.AE_LN_DESC_AEHL	   C20_JOURNAL_LINE_DESCR,
	SQ_XLA_TRANSACTION_ENTITIES.TRANSACTION_NUMBER	   C21_SOURCE_TRANSACTION_NUM,
	CASE WHEN SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_DL = 200 THEN 
   CASE WHEN SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL IN ('AP_INV_DIST','AP_PREPAY') THEN
       CASE WHEN SQ_XLA_AE_LINES_HEADER.ACCT_CLASS_CD_AEHL = 'LIABILITY' THEN
             SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL||'~'||'LIABILITY'||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL)
        ELSE 
             SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL||'~'||'EXPENSE'||'~'|| TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL) 
	    END
    ELSE
        SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL||'~'||SQ_XLA_AE_LINES_HEADER.ACCT_CLASS_CD_AEHL||'~'||
             CASE WHEN SQ_XLA_AE_LINES_HEADER.EVENT_TYPE_CODE_AEHL IN ('PAYMENT CANCELLED','REFUND CANCELLED') THEN
                 'PMTCANCEL'||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL) 
             ELSE TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL)
             END
    END
WHEN SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_DL = 222 THEN
    CASE WHEN SQ_XLA_AE_LINES_HEADER.EVENT_TYPE_CODE_AEHL='RECP_REVERSE' THEN
      CASE WHEN SQ_XLA_AE_LINES_HEADER.UPG_BATCH_ID_AEHL > 0 THEN 
	     SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL)
      ELSE 
	      SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL||'~'||'RECEIPTREVERSE'||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL) 
      END
    ELSE 
	      SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL)
    END
WHEN SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_DL = 140 THEN    
      'FA~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.LEDGER_ID_AEHL)||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL) ||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_2_DL) ||
        CASE WHEN (SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_3_DL IS NULL) THEN '' ELSE ('~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_3_DL)||'~'|| SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_CHAR_4_DL||'~'|| TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_5_DL)) end
WHEN SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_DL = 275 THEN    
        TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL)||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_2_DL) 
WHEN SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_DL ='201' THEN 
        TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL)
ELSE
   SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL || '~' || TO_CHAR(SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL)
END	   C22_SOURCE_DISTRIBUTION_ID,
	COALESCE(SQ_XLA_AP_INV_ALL.INVOICE_NUM,SQ_XLA_RA_TRX.TRX_NUMBER)	   C23_APPLIED_TO_TXN_NUMBER,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_1	   C24_SUPPORT_REF1_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_2	   C25_SUPPORT_REF2_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_3	   C26_SUPPORT_REF3_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_4	   C27_SUPPORT_REF4_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_5	   C28_SUPPORT_REF5_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_6	   C29_SUPPORT_REF6_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_7	   C30_SUPPORT_REF7_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_8	   C31_SUPPORT_REF8_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_9	   C32_SUPPORT_REF9_ID,
	SQ_XLA_AE_LN_ACS.SUPPORT_REF_10	   C33_SUPPORT_REF10_ID,
	SQ_XLA_AE_LINES_HEADER.BUDGET_VERSION_ID_AEHL	   C34_BUDGET_ID,
	DECODE(SQ_XLA_AE_LINES_HEADER.UNROUNDED_ENTERED_DR_DL,NULL,0.0,SQ_XLA_AE_LINES_HEADER.UNROUNDED_ENTERED_DR_DL)  - DECODE(SQ_XLA_AE_LINES_HEADER.UNROUNDED_ENTERED_CR_DL,NULL,0.0,SQ_XLA_AE_LINES_HEADER.UNROUNDED_ENTERED_CR_DL)	   C35_SLA_DOC_AMT,
	DECODE(SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_DR_DL, NULL,0.0,SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_DR_DL) - DECODE(SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_CR_DL,NULL, 0.0,SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_CR_DL)	   C36_SLA_LOC_AMT,
	CASE WHEN (DECODE(SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_DR_DL, NULL,0.0,SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_DR_DL) - DECODE(SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_CR_DL,NULL, 0.0,SQ_XLA_AE_LINES_HEADER.UNROUNDED_ACCT_CR_DL)) < 0 THEN 'CREDIT' ELSE 'DEBIT'END	   C37_DB_CR_IND,
	SQ_XLA_AE_LINES_HEADER.DELETE_FLG	   C38_DELETE_FLG,
	SQ_XLA_AE_LINES_HEADER.CURRENCY_CODE_AEHL	   C39_DOC_CURR_CODE,
	SQ_XLA_AE_LINES_HEADER.CURRENCY_CODE_GL	   C40_LOC_CURR_CODE,
	SQ_XLA_AE_LINES_HEADER.CURR_CNVR_RATE_AEHL	   C41_LOC_EXCHANGE_RATE,
	SQ_XLA_AE_LINES_HEADER.CURR_CNVR_TYPE_AEHL	   C42_LOC_EXCH_RATE_TYPE,
	DECODE(SQ_XLA_AE_LINES_HEADER.CURR_CNVR_DATE_AEHL,NULL,SQ_XLA_AE_LINES_HEADER.ACCOUNTING_DATE_AEHL,SQ_XLA_AE_LINES_HEADER.CURR_CNVR_DATE_AEHL)	   C43_EXCHANGE_DT,
	TO_CHAR(SQ_XLA_AE_LINES_HEADER.CRTD_BY_LN_AEHL)	   C44_CREATED_BY_ID,
	TO_CHAR(SQ_XLA_AE_LINES_HEADER.LAST_UPD_BY_LN_AEHL)	   C45_CHANGED_BY_ID,
	SQ_XLA_AE_LINES_HEADER.CRTD_DT_LN_AEHL	   C46_CREATED_ON_DT,
	SQ_XLA_AE_LINES_HEADER.LAST_UPD_DT_LN_AEHL	   C47_CHANGED_ON_DT,
	SQ_XLA_AE_LINES_HEADER.LAST_UPD_DT_HDR_AEHL	   C48_AUX1_CHANGED_ON_DT,
	SQ_GL_HDR_IMP_REF.LAST_UPDATE_DATE	   C49_AUX2_CHANGED_ON_DT,
	TO_CHAR(SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_DL)||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.REF_AE_HEADER_ID_DL)||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.TEMP_LINE_NUM_DL)||'~'||TO_CHAR(SQ_XLA_AE_LINES_HEADER.AE_HDR_ID_DL)	   C50_INTEGRATION_ID,
	COALESCE(SQ_XLA_OZF_CLAIM_SETTLEMENTS.ORG_ID,SQ_XLA_OZF_ACCRUALS.ORG_ID,SQ_XLA_AP_INV_ALL.ORG_ID,SQ_XLA_CST.ORGANIZATION_ID,SQ_XLA_RA_TRX.ORG_ID,SQ_XLA_TRANSACTION_ENTITIES.SECURITY_ID_INT_1)	   C51_X_ORG_ID,
	COALESCE(TO_CHAR(SQ_XLA_RA_TRX.SALES_ORDER),TO_CHAR(SQ_XLA_CST.ORDER_NUMBER),TO_CHAR(SQ_XLA_AP_INV_ALL.PO_NUMBER))	   C52_X_ORDER_NUMBER,
	COALESCE(SQ_XLA_RA_TRX.SALES_ORDER_DATE,SQ_XLA_CST.ORDERED_DATE)	   C53_X_ORDER_DATE,
	COALESCE(SQ_XLA_CST.INVENTORY_ITEM_ID,SQ_XLA_OZF_ACCRUALS.PRODUCT_ID,SQ_XLA_OZF_CLAIM_SETTLEMENTS.PRODUCT_ID,SQ_XLA_RA_TRX.INVENTORY_ITEM_ID)	   C54_X_INVENTORY_ITEM_ID,
	COALESCE(SQ_XLA_RA_TRX.TERM_ID,SQ_XLA_CST.PAYMENT_TERM_ID,SQ_XLA_AP_INV_ALL.TERMS_ID)	   C55_X_PAY_TERMS_ID,
	COALESCE(SQ_XLA_AP_INV_ALL.INVOICE_DATE,SQ_XLA_RA_TRX.TRX_DATE)	   C56_X_INVOICE_DATE,
	SQ_XLA_AP_INV_ALL.INVOICE_RECEIVED_DATE	   C57_X_INVOICE_RECEIPT_DATE,
	CASE WHEN SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_DL=682 THEN 
COALESCE(SQ_XLA_OZF_CLAIM_SETTLEMENTS.ORDER_LINE_ID,SQ_XLA_OZF_ACCRUALS.ORDER_LINE_ID)
ELSE
SQ_XLA_TRANSACTION_ENTITIES.SOURCE_ID_INT_1
END	   C58_X_SOURCE_LINE_ID,
	SQ_XLA_AP_INV_ALL.DESCRIPTION	   C59_X_SOURCE_LINE_ITEM_TEXT,
	COALESCE(SQ_XLA_RA_TRX.CLAIM_NUMBER,SQ_XLA_OZF_CLAIM_SETTLEMENTS.CLAIM_NUMBER)	   C60_X_CLAIM_NUMBER,
	COALESCE(SQ_XLA_RA_TRX.CLAIM_DATE,SQ_XLA_OZF_CLAIM_SETTLEMENTS.CLAIM_DATE)	   C61_X_CLAIM_DATE,
	COALESCE(SQ_XLA_OZF_CLAIM_SETTLEMENTS.FUND_NUMBER,SQ_XLA_OZF_ACCRUALS.FUND_NUMBER)	   C62_X_FUND_NUMBER,
	COALESCE(SQ_XLA_AP_INV_ALL.QUANTITY_DELIVERED,SQ_XLA_CST.PRIMARY_QUANTITY,SQ_XLA_RA_TRX.X_TRX_QUANTITY)	   C63_X_TRX_QUANTITY,
	CASE WHEN SQ_XLA_RA_TRX.TYPE='INV' AND NVL(SQ_XLA_RA_TRX.INTERFACE_LINE_ATTRIBUTE11,'0') <> '0'
THEN 'Y'
ELSE  'N'
END	   C64_X_DISCOUNT_FLAG,
	COALESCE(SQ_XLA_CST.X_SALESREP_ID, SQ_XLA_RA_TRX.X_SALESREP_ID)	   C65_X_SALESREP_ID,
	SQ_XLA_RA_TRX.LOC_COST_AMT	   C66_X_COGS_AMT,
	SQ_XLA_RA_TRX.CUST_ACCT_SITE_ID	   C67_X_CUSTOMER_SHIP_TO_ID,
	NVL(SQ_XLA_RA_TRX.ORDER_TYPE_ID, SQ_XLA_CST.ORDER_TYPE_ID)	   C68_X_ORDER_TYPE_ID,
	SQ_XLA_RA_TRX.SHIP_TO_SITE_USE_ID	   C69_X_SHIP_TO_SITE_USE_ID,
	SQ_XLA_RA_TRX.BILL_TO_SITE_USE_ID	   C70_X_BILL_TO_SITE_USE_ID,
	SQ_XLA_RA_TRX.CUST_TRX_TYPE_ID	   C71_X_DOC_TYPE_ID,
	SQ_XLA_RA_TRX.FREIGHT_TERMS_CODE	   C72_X_FREIGHT_TERMS_CODE,
	SQ_XLA_RA_TRX.REASON_CODE	   C73_X_REASON_CODE,
	null	   C74_X_TERR_ID,
	COALESCE(SQ_XLA_CST.X_SHIP_TO_ORG_ID,SQ_XLA_RA_TRX.X_SHIP_TO_ORG_ID)	   C75_X_SHIP_TO_ORG_ID,
	COALESCE(SQ_XLA_CST.X_SOLD_TO_ORG_ID,SQ_XLA_RA_TRX.X_SOLD_TO_ORG_ID)	   C76_X_SOLD_TO_ORG_ID,
	COALESCE(SQ_XLA_RA_TRX.X_GENERIC_CUSTOMER_ID,SQ_XLA_CST.X_GENERIC_CUSTOMER_ID)	   C77_X_GENERIC_CUSTOMER_ID,
	SQ_GL_HDR_IMP_REF.X_JOURNAL_NAME	   C78_X_JOURNAL_NAME,
	COALESCE(SQ_XLA_CST.X_CUST_PO_NUMBER,SQ_XLA_RA_TRX.X_CUST_PO_NUMBER)	   C79_X_CUST_PO_NUMBER,
	COALESCE(SQ_XLA_RA_TRX.ORDER_SOURCE_ID,SQ_XLA_CST.ORDER_SOURCE_ID,'0')	   C80_X_ORDER_SOURCE_ID,
	SQ_XLA_AE_LINES_HEADER.GL_TRANF_STS_CODE_AEHL	   C106_GL_TRANF_STS_CODE_AEHL,
	SQ_GL_HDR_IMP_REF.STATUS	   C107_STATUS,
	SQ_XLA_AE_LINES_HEADER.BALANCE_TYPE_CODE_AEHL	   C108_BALANCE_TYPE_CODE_AEHL,
	SQ_GL_HDR_IMP_REF.ENCUMBRANCE_TYPE_ID	   C109_ENCUMBRANCE_TYPE_ID,
	SQ_XLA_AE_LINES_HEADER.ACCT_TYP_GL_CODE_COMB	   C110_ACCT_TYP_GL_CODE_COMB
from	(((((((
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_SQ_XLA_DISTRIBUTION_LINKS
*/


select 
	  

	   
	   XLA_AE_HEADERS.AE_HEADER_ID AE_HEADER_ID_AEHL,
	XLA_AE_HEADERS.ENTITY_ID ENTITY_ID_AEHL,
	XLA_AE_HEADERS.LEDGER_ID LEDGER_ID_AEHL,
	XLA_AE_HEADERS.APPLICATION_ID APPLICATION_ID_AEHL,
	XLA_AE_HEADERS.JE_CATEGORY_NAME JE_CATGRY_NAME_AEHL,
	XLA_AE_HEADERS.PERIOD_NAME PERIOD_NAME_AEHL,
	XLA_AE_HEADERS.ACCOUNTING_DATE ACCOUNTING_DATE_AEHL,
	XLA_AE_HEADERS.GL_TRANSFER_DATE GL_TRANF_DATE_AEHL,
	XLA_AE_HEADERS.GL_TRANSFER_STATUS_CODE GL_TRANF_STS_CODE_AEHL,
	XLA_AE_HEADERS.LAST_UPDATED_BY LAST_UPD_BY_HDR_AEHL,
	XLA_AE_HEADERS.CREATED_BY CREATED_BY_HDR_AEHL,
	XLA_AE_HEADERS.LAST_UPDATE_DATE LAST_UPD_DT_HDR_AEHL,
	XLA_AE_HEADERS.CREATION_DATE CREATION_DATE_HDR_AEHL,
	XLA_AE_HEADERS.UPG_BATCH_ID UPG_BATCH_ID_AEHL,
	XLA_AE_HEADERS.EVENT_TYPE_CODE EVENT_TYPE_CODE_AEHL,
	XLA_AE_LINES.ACCOUNTING_CLASS_CODE ACCT_CLASS_CD_AEHL,
	XLA_AE_LINES.PARTY_ID PARTY_ID_AEHL,
	XLA_AE_LINES.PARTY_TYPE_CODE PARTY_TYPE_CODE_AEHL,
	XLA_AE_LINES.CODE_COMBINATION_ID CODE_COMB_ID_AEHL,
	XLA_AE_LINES.AE_LINE_NUM AE_LINE_NUM_AEHL,
	XLA_AE_LINES.GL_SL_LINK_ID GL_SL_LINK_ID_AEHL,
	XLA_AE_LINES.PARTY_SITE_ID PARTY_SITE_ID_AEHL,
	XLA_AE_LINES.GL_SL_LINK_TABLE GL_SL_LINK_TBL_AEHL,
	XLA_AE_LINES.SOURCE_ID SOURCE_ID_AEHL,
	XLA_AE_LINES.SOURCE_TABLE SOURCE_TABLE_AEHL,
	XLA_AE_LINES.CURRENCY_CONVERSION_RATE CURR_CNVR_RATE_AEHL,
	XLA_AE_LINES.CURRENCY_CONVERSION_TYPE CURR_CNVR_TYPE_AEHL,
	XLA_AE_LINES.CURRENCY_CONVERSION_DATE CURR_CNVR_DATE_AEHL,
	XLA_AE_LINES.CURRENCY_CODE CURRENCY_CODE_AEHL,
	GL_CODE_COMBINATIONS.ACCOUNT_TYPE ACCT_TYP_GL_CODE_COMB,
	XLA_AE_LINES.DESCRIPTION AE_LN_DESC_AEHL,
	XLA_AE_HEADERS.DESCRIPTION AE_HDR_DESC_AEHL,
	XLA_AE_HEADERS.BALANCE_TYPE_CODE BALANCE_TYPE_CODE_AEHL,
	XLA_AE_HEADERS.BUDGET_VERSION_ID BUDGET_VERSION_ID_AEHL,
	XLA_AE_LINES.LAST_UPDATED_BY LAST_UPD_BY_LN_AEHL,
	XLA_AE_LINES.LAST_UPDATE_DATE LAST_UPD_DT_LN_AEHL,
	XLA_AE_LINES.CREATED_BY CRTD_BY_LN_AEHL,
	XLA_AE_LINES.CREATION_DATE CRTD_DT_LN_AEHL,
	XLA_DISTRIBUTION_LINKS.TEMP_LINE_NUM TEMP_LINE_NUM_DL,
	XLA_DISTRIBUTION_LINKS.EVENT_CLASS_CODE EVENT_CLASS_CODE_DL,
	XLA_DISTRIBUTION_LINKS.REF_AE_HEADER_ID REF_AE_HEADER_ID_DL,
	XLA_DISTRIBUTION_LINKS.EVENT_TYPE_CODE EVENT_TYPE_CODE_DL,
	XLA_DISTRIBUTION_LINKS.AE_LINE_NUM AE_LINE_NUM_DL,
	XLA_DISTRIBUTION_LINKS.AE_HEADER_ID AE_HDR_ID_DL,
	XLA_DISTRIBUTION_LINKS.APPLICATION_ID APPLICATION_ID_DL,
	XLA_DISTRIBUTION_LINKS.UNROUNDED_ACCOUNTED_DR UNROUNDED_ACCT_DR_DL,
	XLA_DISTRIBUTION_LINKS.UNROUNDED_ACCOUNTED_CR UNROUNDED_ACCT_CR_DL,
	XLA_DISTRIBUTION_LINKS.UNROUNDED_ENTERED_DR UNROUNDED_ENTERED_DR_DL,
	XLA_DISTRIBUTION_LINKS.UNROUNDED_ENTERED_CR UNROUNDED_ENTERED_CR_DL,
	XLA_DISTRIBUTION_LINKS.SOURCE_DISTRIBUTION_ID_NUM_5 SOURCE_DIST_ID_NUM_5_DL,
	XLA_DISTRIBUTION_LINKS.SOURCE_DISTRIBUTION_ID_NUM_3 SOURCE_DIST_ID_NUM_3_DL,
	XLA_DISTRIBUTION_LINKS.SOURCE_DISTRIBUTION_TYPE SOURCE_DIST_TYPE_DL,
	XLA_DISTRIBUTION_LINKS.SOURCE_DISTRIBUTION_ID_CHAR_4 SOURCE_DIST_ID_CHAR_4_DL,
	XLA_DISTRIBUTION_LINKS.APPLIED_TO_DISTRIBUTION_TYPE APPLIED_TO_DIST_TYPE_DL,
	XLA_DISTRIBUTION_LINKS.SOURCE_DISTRIBUTION_ID_NUM_2 SOURCE_DIST_ID_NUM_2_DL,
	XLA_DISTRIBUTION_LINKS.SOURCE_DISTRIBUTION_ID_NUM_4 SOURCE_DIST_ID_NUM_4_DL,
	XLA_DISTRIBUTION_LINKS.SOURCE_DISTRIBUTION_ID_NUM_1 SOURCE_DIST_ID_NUM_1_DL,
	XLA_DISTRIBUTION_LINKS.APPLIED_TO_SOURCE_ID_NUM_1 APPLIED_TO_SRC_ID_NUM_1_DL,
	FND_APPLICATION.APPLICATION_SHORT_NAME APPLICATION_SHORT_NAME_FND,
	XLA_SUBLEDGERS.JE_SOURCE_NAME JE_SOURCE_NAME_DL,
	GL_LEDGERS.PERIOD_SET_NAME PERIOD_SET_NAME_GL,
	GL_LEDGERS.CURRENCY_CODE CURRENCY_CODE_GL,
	
'N'
 DELETE_FLG,
	XLA_AE_LINES.DISPLAYED_LINE_NUMBER DISPLAYED_LINE_NUMBER
from	(((APPS.XLA_DISTRIBUTION_LINKS    XLA_DISTRIBUTION_LINKS INNER JOIN ((APPS.XLA_AE_LINES    XLA_AE_LINES INNER JOIN APPS.XLA_AE_HEADERS    XLA_AE_HEADERS ON XLA_AE_LINES.AE_HEADER_ID=XLA_AE_HEADERS.AE_HEADER_ID AND XLA_AE_LINES.APPLICATION_ID=XLA_AE_HEADERS.APPLICATION_ID) INNER JOIN APPS.GL_CODE_COMBINATIONS    GL_CODE_COMBINATIONS ON XLA_AE_LINES.CODE_COMBINATION_ID=GL_CODE_COMBINATIONS.CODE_COMBINATION_ID) ON XLA_DISTRIBUTION_LINKS.AE_HEADER_ID=XLA_AE_LINES.AE_HEADER_ID 
AND XLA_DISTRIBUTION_LINKS.AE_LINE_NUM=XLA_AE_LINES.AE_LINE_NUM 
AND XLA_DISTRIBUTION_LINKS.APPLICATION_ID=XLA_AE_LINES.APPLICATION_ID) INNER JOIN APPS.FND_APPLICATION    FND_APPLICATION ON XLA_DISTRIBUTION_LINKS.APPLICATION_ID=FND_APPLICATION.APPLICATION_ID) LEFT OUTER JOIN APPS.XLA_SUBLEDGERS    XLA_SUBLEDGERS ON XLA_DISTRIBUTION_LINKS.APPLICATION_ID=XLA_SUBLEDGERS.APPLICATION_ID) INNER JOIN APPS.GL_LEDGERS    GL_LEDGERS ON XLA_AE_HEADERS.LEDGER_ID=GL_LEDGERS.LEDGER_ID
where	(1=1)

And (XLA_AE_HEADERS.ACCOUNTING_ENTRY_STATUS_CODE='F')
 And (

(XLA_AE_HEADERS.LAST_UPDATE_DATE>= TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS'))

)
 And (XLA_DISTRIBUTION_LINKS.APPLICATION_ID IN (#BIAPPS.SUBLEDGER_MODULE_LIST))
 And (('NULL' IN ('#BIAPPS.LEDGER_ID_LIST')
    OR ('NULL' NOT IN ('#BIAPPS.LEDGER_ID_LIST')
        AND 
        GL_LEDGERS.LEDGER_ID IN (#BIAPPS.LEDGER_ID_LIST)
       )
)
AND
('__NONE__'  IN (#BIAPPS.LEDGER_TYPE_LIST)
  OR  ('__NONE__' NOT IN (#BIAPPS.LEDGER_TYPE_LIST)
      AND 
      GL_LEDGERS.LEDGER_CATEGORY_CODE IN (#BIAPPS.LEDGER_TYPE_LIST)
      )
))







)    SQ_XLA_AE_LINES_HEADER LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_XLA_TRANSACTION_ENTITIES
*/

SELECT * FROM 
     #BIAPPS.SLA_SCHEMA.XLA_TRANSACTION_ENTITIES
 XTE


)    SQ_XLA_TRANSACTION_ENTITIES ON SQ_XLA_AE_LINES_HEADER.ENTITY_ID_AEHL=SQ_XLA_TRANSACTION_ENTITIES.ENTITY_ID AND SQ_XLA_AE_LINES_HEADER.APPLICATION_ID_AEHL=SQ_XLA_TRANSACTION_ENTITIES.APPLICATION_ID) LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_GL_HDR_IMP_REF
*/


select 
	  

	   DISTINCT
	   GL_IMPORT_REFERENCES.GL_SL_LINK_ID GL_SL_LINK_ID,
	GL_IMPORT_REFERENCES.GL_SL_LINK_TABLE GL_SL_LINK_TABLE,
	GL_JE_HEADERS.LEDGER_ID LEDGER_ID,
	GL_JE_HEADERS.LAST_UPDATE_DATE LAST_UPDATE_DATE,
	GL_JE_HEADERS.STATUS STATUS,
	GL_JE_HEADERS.ENCUMBRANCE_TYPE_ID ENCUMBRANCE_TYPE_ID,
	GL_JE_HEADERS.NAME X_JOURNAL_NAME
from	APPS.GL_IMPORT_REFERENCES    GL_IMPORT_REFERENCES INNER JOIN APPS.GL_JE_HEADERS    GL_JE_HEADERS ON GL_IMPORT_REFERENCES.JE_HEADER_ID=GL_JE_HEADERS.JE_HEADER_ID
where	(1=1)

And (

(GL_JE_HEADERS.LAST_UPDATE_DATE> TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS'))

)







)    SQ_GL_HDR_IMP_REF ON SQ_XLA_AE_LINES_HEADER.GL_SL_LINK_ID_AEHL=SQ_GL_HDR_IMP_REF.GL_SL_LINK_ID AND SQ_XLA_AE_LINES_HEADER.GL_SL_LINK_TBL_AEHL=SQ_GL_HDR_IMP_REF.GL_SL_LINK_TABLE AND SQ_XLA_AE_LINES_HEADER.LEDGER_ID_AEHL=SQ_GL_HDR_IMP_REF.LEDGER_ID) LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_XLA_AE_LN_ACS.MAX
*/


select 
	  

	   
	   XLA_AE_LINE_ACS.AE_LINE_NUM AE_LINE_NUM,
	XLA_AE_LINE_ACS.AE_HEADER_ID AE_HEADER_ID,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF1' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_1,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF2' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_2,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF3' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_3,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF4' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_4,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF5' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_5,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF6' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_6,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF7' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_7,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF8' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_8,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF9' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_9,
	MAX(CASE WHEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE = '#BIAPPS.SUPPORT_REF10' THEN XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_CODE||'~'||XLA_AE_LINE_ACS.ANALYTICAL_CRITERION_TYPE_CODE||'~'|| XLA_AE_LINE_ACS.AMB_CONTEXT_CODE||'~'||XLA_AE_LINE_ACS.AC1||'~'||XLA_AE_LINE_ACS.AC2||'~'||XLA_AE_LINE_ACS.AC3||'~'||XLA_AE_LINE_ACS.AC4||'~'||XLA_AE_LINE_ACS.AC5  END) SUPPORT_REF_10
from	APPS.XLA_AE_LINE_ACS    XLA_AE_LINE_ACS INNER JOIN APPS.XLA_AE_HEADERS    XLA_AE_HEADERS ON XLA_AE_LINE_ACS.AE_HEADER_ID=XLA_AE_HEADERS.AE_HEADER_ID
where	(1=1)

And (

(XLA_AE_HEADERS.LAST_UPDATE_DATE>= TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS'))

)


Group By XLA_AE_LINE_ACS.AE_LINE_NUM,
 XLA_AE_LINE_ACS.AE_HEADER_ID





)    SQ_XLA_AE_LN_ACS ON SQ_XLA_AE_LINES_HEADER.AE_HDR_ID_DL=SQ_XLA_AE_LN_ACS.AE_HEADER_ID AND SQ_XLA_AE_LINES_HEADER.AE_LINE_NUM_DL=SQ_XLA_AE_LN_ACS.AE_LINE_NUM) LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_RA_TRX_ALL
*/


select 
	  

	   
	   RA_CUSTOMER_TRX_LINES_ALL.SALES_ORDER SALES_ORDER,
	RA_CUSTOMER_TRX_LINES_ALL.SALES_ORDER_DATE SALES_ORDER_DATE,
	RA_CUSTOMER_TRX_ALL.TERM_ID TERM_ID,
	RA_CUSTOMER_TRX_ALL.TRX_NUMBER TRX_NUMBER,
	RA_CUSTOMER_TRX_ALL.TRX_DATE TRX_DATE,
	RA_CUST_TRX_LINE_GL_DIST_ALL.CUST_TRX_LINE_GL_DIST_ID CUST_TRX_LINE_GL_DIST_ID,
	RA_CUSTOMER_TRX_LINES_ALL.WAREHOUSE_ID ORG_ID,
	RA_CUSTOMER_TRX_LINES_ALL.INVENTORY_ITEM_ID INVENTORY_ITEM_ID,
	DECODE(NVL(RA_CUSTOMER_TRX_LINES_ALL.INTERFACE_LINE_ATTRIBUTE11,'0'),'0',NVL(RA_CUSTOMER_TRX_LINES_ALL.QUANTITY_INVOICED,0)+NVL(RA_CUSTOMER_TRX_LINES_ALL.QUANTITY_CREDITED,0))* NVL(MTL_UOM_CONVERSIONS.CONVERSION_RATE,1.00) X_TRX_QUANTITY,
	RA_CUST_TRX_TYPES_ALL.TYPE TYPE,
	RA_CUSTOMER_TRX_LINES_ALL.INTERFACE_LINE_ATTRIBUTE11 INTERFACE_LINE_ATTRIBUTE11,
	SQ_XLA_RA_COST.LOC_COST_AMT LOC_COST_AMT,
	HZ_CUST_SITE_USES_ALL.CUST_ACCT_SITE_ID CUST_ACCT_SITE_ID,
	RA_CUSTOMER_TRX_ALL.SHIP_TO_SITE_USE_ID SHIP_TO_SITE_USE_ID,
	RA_CUSTOMER_TRX_ALL.BILL_TO_SITE_USE_ID BILL_TO_SITE_USE_ID,
	'ACCT_DOC~RECEIVABLE~ORIGINAL~'||RA_CUSTOMER_TRX_ALL.CUST_TRX_TYPE_ID||'~'|| RA_CUSTOMER_TRX_ALL.ORG_ID CUST_TRX_TYPE_ID,
	'SALES_ORDLNS~'||OE_ORDER_HEADERS_ALL.ORDER_CATEGORY_CODE||'~'||OE_ORDER_HEADERS_ALL.ORDER_TYPE_ID||'~'||DECODE(OE_ORDER_HEADERS_ALL.DROP_SHIP_FLAG,'Y','DROP SHIP','SELF SHIP') ORDER_TYPE_ID,
	OE_ORDER_LINES_ALL.FREIGHT_TERMS_CODE FREIGHT_TERMS_CODE,
	COALESCE(RA_CUSTOMER_TRX_LINES_ALL.REASON_CODE,RA_CUSTOMER_TRX_ALL.REASON_CODE,RA_CUSTOMER_TRX_LINES_ALL.INTERFACE_LINE_ATTRIBUTE7,RA_CUSTOMER_TRX_ALL.INTERFACE_HEADER_ATTRIBUTE7) REASON_CODE,
	OE_ORDER_HEADERS_ALL.ATTRIBUTE19 X_GENERIC_CUSTOMER_ID,
	OE_ORDER_LINES_ALL.SALESREP_ID X_SALESREP_ID,
	OE_ORDER_LINES_ALL.SHIP_TO_ORG_ID X_SHIP_TO_ORG_ID,
	OE_ORDER_LINES_ALL.SOLD_TO_ORG_ID X_SOLD_TO_ORG_ID,
	OE_ORDER_HEADERS_ALL.CUST_PO_NUMBER X_CUST_PO_NUMBER,
	CASE WHEN OE_ORDER_HEADERS_ALL.ORDER_SOURCE_ID IS NOT NULL
THEN 'SALES_ORDSRC~'||TO_CHAR(OE_ORDER_HEADERS_ALL.ORDER_SOURCE_ID)
ELSE 
'0'
END ORDER_SOURCE_ID,
	OZF_CLAIMS_ALL.CLAIM_NUMBER CLAIM_NUMBER,
	OZF_CLAIMS_ALL.CLAIM_DATE CLAIM_DATE
from	APPS.RA_CUSTOMER_TRX_ALL   RA_CUSTOMER_TRX_ALL, APPS.RA_CUSTOMER_TRX_LINES_ALL   RA_CUSTOMER_TRX_LINES_ALL, APPS.RA_CUST_TRX_LINE_GL_DIST_ALL   RA_CUST_TRX_LINE_GL_DIST_ALL, APPS.MTL_UOM_CONVERSIONS   MTL_UOM_CONVERSIONS, APPS.RA_CUST_TRX_TYPES_ALL   RA_CUST_TRX_TYPES_ALL, 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_RA_COST
*/


select 
	  

	   
	   RA_CUSTOMER_TRX_LINES_ALL.CUSTOMER_TRX_LINE_ID CUSTOMER_TRX_LINE_ID,
	SUM(MTL_TRANSACTION_ACCOUNTS.BASE_TRANSACTION_VALUE) LOC_COST_AMT
from	APPS.RA_CUSTOMER_TRX_LINES_ALL   RA_CUSTOMER_TRX_LINES_ALL, APPS.MTL_TRANSACTION_ACCOUNTS   MTL_TRANSACTION_ACCOUNTS, APPS.MTL_MATERIAL_TRANSACTIONS   MTL_MATERIAL_TRANSACTIONS, APPS.GL_CODE_COMBINATIONS   GL_CODE_COMBINATIONS
where	(1=1)
 And (GL_CODE_COMBINATIONS.CODE_COMBINATION_ID=MTL_TRANSACTION_ACCOUNTS.REFERENCE_ACCOUNT)
AND (MTL_MATERIAL_TRANSACTIONS.TRANSACTION_ID=MTL_TRANSACTION_ACCOUNTS.TRANSACTION_ID)
AND (RA_CUSTOMER_TRX_LINES_ALL.INTERFACE_LINE_ATTRIBUTE6=MTL_MATERIAL_TRANSACTIONS.TRX_SOURCE_LINE_ID)

And (MTL_MATERIAL_TRANSACTIONS.TRANSACTION_TYPE_ID IN (15,33))
 And (GL_CODE_COMBINATIONS.ACCOUNT_TYPE='E')
 And (RA_CUSTOMER_TRX_LINES_ALL.INTERFACE_LINE_ATTRIBUTE11='0')


Group By RA_CUSTOMER_TRX_LINES_ALL.CUSTOMER_TRX_LINE_ID





)   SQ_XLA_RA_COST, APPS.HZ_CUST_SITE_USES_ALL   HZ_CUST_SITE_USES_ALL, APPS.OE_ORDER_LINES_ALL   OE_ORDER_LINES_ALL, APPS.OE_ORDER_HEADERS_ALL   OE_ORDER_HEADERS_ALL, APPS.OZF_CLAIMS_ALL   OZF_CLAIMS_ALL
where	(1=1)
 And (OE_ORDER_HEADERS_ALL.HEADER_ID (+)=OE_ORDER_LINES_ALL.HEADER_ID)
AND (RA_CUST_TRX_LINE_GL_DIST_ALL.CUSTOMER_TRX_LINE_ID=RA_CUSTOMER_TRX_LINES_ALL.CUSTOMER_TRX_LINE_ID (+))
AND (RA_CUST_TRX_LINE_GL_DIST_ALL.CUSTOMER_TRX_ID=RA_CUSTOMER_TRX_ALL.CUSTOMER_TRX_ID)
AND (RA_CUSTOMER_TRX_LINES_ALL.UOM_CODE=MTL_UOM_CONVERSIONS.UOM_CODE (+) AND RA_CUSTOMER_TRX_LINES_ALL.INVENTORY_ITEM_ID=MTL_UOM_CONVERSIONS.INVENTORY_ITEM_ID (+))
AND (RA_CUST_TRX_TYPES_ALL.CUST_TRX_TYPE_ID=RA_CUSTOMER_TRX_ALL.CUST_TRX_TYPE_ID
AND RA_CUSTOMER_TRX_ALL.ORG_ID=RA_CUST_TRX_TYPES_ALL.ORG_ID)
AND (RA_CUSTOMER_TRX_LINES_ALL.CUSTOMER_TRX_LINE_ID=SQ_XLA_RA_COST.CUSTOMER_TRX_LINE_ID (+))
AND (RA_CUSTOMER_TRX_ALL.SHIP_TO_SITE_USE_ID=HZ_CUST_SITE_USES_ALL.SITE_USE_ID (+))
AND ((OE_ORDER_LINES_ALL.LINE_ID (+)=TO_NUMBER(REGEXP_REPLACE(RA_CUSTOMER_TRX_LINES_ALL.INTERFACE_LINE_ATTRIBUTE6,'\D',''))))
AND ((CASE WHEN LENGTH(RA_CUSTOMER_TRX_ALL.CT_REFERENCE)=10 THEN	
RA_CUSTOMER_TRX_ALL.CT_REFERENCE	
ELSE	
substr(regexp_replace(RA_CUSTOMER_TRX_ALL.CT_REFERENCE,' ','',1,1),1,regexp_instr(regexp_replace(RA_CUSTOMER_TRX_ALL.CT_REFERENCE,' ','',1,1),'[^0-9a-zA-Z]',1)-1)	
END)	
=OZF_CLAIMS_ALL.CLAIM_NUMBER (+))








)    SQ_XLA_RA_TRX ON SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL=SQ_XLA_RA_TRX.CUST_TRX_LINE_GL_DIST_ID AND SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL='RA_CUST_TRX_LINE_GL_DIST_ALL') LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_AP_INVOICES_ALL
*/


select 
	  

	   
	   AP_INVOICES_ALL.INVOICE_ID INVOICE_ID,
	PO_HEADERS_ALL.SEGMENT1 PO_NUMBER,
	AP_INVOICES_ALL.DESCRIPTION DESCRIPTION,
	AP_INVOICES_ALL.INVOICE_DATE INVOICE_DATE,
	AP_INVOICES_ALL.TERMS_ID TERMS_ID,
	AP_INVOICES_ALL.VENDOR_SITE_ID VENDOR_SITE_ID,
	AP_INVOICES_ALL.PARTY_ID PARTY_ID,
	NVL(AP_INVOICES_ALL.INVOICE_RECEIVED_DATE,AP_INVOICES_ALL.CREATION_DATE) INVOICE_RECEIVED_DATE,
	AP_INVOICE_DISTRIBUTIONS_ALL.INVOICE_DISTRIBUTION_ID INVOICE_DISTRIBUTION_ID,
	AP_INVOICES_ALL.INVOICE_NUM INVOICE_NUM,
	PO_DISTRIBUTIONS_ALL.DESTINATION_ORGANIZATION_ID ORG_ID,
	PO_DISTRIBUTIONS_ALL.QUANTITY_DELIVERED QUANTITY_DELIVERED
from	APPS.AP_INVOICES_ALL   AP_INVOICES_ALL, APPS.AP_INVOICE_DISTRIBUTIONS_ALL   AP_INVOICE_DISTRIBUTIONS_ALL, APPS.PO_DISTRIBUTIONS_ALL   PO_DISTRIBUTIONS_ALL, APPS.PO_HEADERS_ALL   PO_HEADERS_ALL
where	(1=1)
 And (AP_INVOICES_ALL.INVOICE_ID=AP_INVOICE_DISTRIBUTIONS_ALL.INVOICE_ID)
AND (AP_INVOICE_DISTRIBUTIONS_ALL.PO_DISTRIBUTION_ID=PO_DISTRIBUTIONS_ALL.PO_DISTRIBUTION_ID (+))
AND (PO_DISTRIBUTIONS_ALL.PO_HEADER_ID=PO_HEADERS_ALL.PO_HEADER_ID (+))








)    SQ_XLA_AP_INV_ALL ON SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL=SQ_XLA_AP_INV_ALL.INVOICE_DISTRIBUTION_ID AND SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL='AP_INV_DIST') LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_OZF_ACCRUAL
*/


select 
	  

	   
	   OZF_FUNDS_ALL_B.FUND_NUMBER FUND_NUMBER,
	OZF_FUNDS_UTILIZED_ALL_B.UTILIZATION_ID UTILIZATION_ID,
	OZF_FUNDS_UTILIZED_ALL_B.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
	OZF_FUNDS_UTILIZED_ALL_B.PRODUCT_ID PRODUCT_ID,
	OZF_FUNDS_UTILIZED_ALL_B.ORDER_LINE_ID ORDER_LINE_ID,
	OZF_FUNDS_UTILIZED_ALL_B.ORG_ID ORG_ID
from	APPS.OZF_FUNDS_UTILIZED_ALL_B   OZF_FUNDS_UTILIZED_ALL_B, APPS.OZF_FUNDS_ALL_B   OZF_FUNDS_ALL_B
where	(1=1)
 And (OZF_FUNDS_UTILIZED_ALL_B.FUND_ID=OZF_FUNDS_ALL_B.FUND_ID)








)    SQ_XLA_OZF_ACCRUALS ON SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL=SQ_XLA_OZF_ACCRUALS.UTILIZATION_ID AND SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL='ACCRUAL') LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_OZF_CLAIM_SETTLEMENT
*/


select 
	  

	   
	   OZF_FUNDS_ALL_B.FUND_NUMBER FUND_NUMBER,
	OZF_FUNDS_UTILIZED_ALL_B.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
	OZF_FUNDS_UTILIZED_ALL_B.PRODUCT_ID PRODUCT_ID,
	OZF_FUNDS_UTILIZED_ALL_B.ORDER_LINE_ID ORDER_LINE_ID,
	OZF_FUNDS_UTILIZED_ALL_B.ORG_ID ORG_ID,
	OZF_CLAIMS_ALL.CLAIM_NUMBER CLAIM_NUMBER,
	OZF_CLAIMS_ALL.CLAIM_DATE CLAIM_DATE,
	OZF_CLAIM_LINES_UTIL_ALL.CLAIM_LINE_UTIL_ID CLAIM_LINE_UTIL_ID
from	APPS.OZF_FUNDS_UTILIZED_ALL_B   OZF_FUNDS_UTILIZED_ALL_B, APPS.OZF_FUNDS_ALL_B   OZF_FUNDS_ALL_B, APPS.OZF_CLAIMS_ALL   OZF_CLAIMS_ALL, APPS.OZF_CLAIM_LINES_ALL   OZF_CLAIM_LINES_ALL, APPS.OZF_CLAIM_LINES_UTIL_ALL   OZF_CLAIM_LINES_UTIL_ALL
where	(1=1)
 And (OZF_FUNDS_UTILIZED_ALL_B.FUND_ID=OZF_FUNDS_ALL_B.FUND_ID)
AND (OZF_CLAIM_LINES_UTIL_ALL.CLAIM_LINE_ID=OZF_CLAIM_LINES_ALL.CLAIM_LINE_ID)
AND (OZF_CLAIMS_ALL.CLAIM_ID=OZF_CLAIM_LINES_ALL.CLAIM_ID)
AND (OZF_CLAIM_LINES_UTIL_ALL.UTILIZATION_ID=OZF_FUNDS_UTILIZED_ALL_B.UTILIZATION_ID)








)    SQ_XLA_OZF_CLAIM_SETTLEMENTS ON SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_ID_NUM_1_DL=SQ_XLA_OZF_CLAIM_SETTLEMENTS.CLAIM_LINE_UTIL_ID AND SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL='CLAIM_SETTLEMENT') LEFT OUTER JOIN 
( /* Subselect from SDE_ORA_SLAJournalFact.W_SLA_XACT_FS_CST
*/


select 
	  

	   
	   OE_ORDER_HEADERS_ALL.ORDER_NUMBER ORDER_NUMBER,
	OE_ORDER_HEADERS_ALL.ORDERED_DATE ORDERED_DATE,
	OE_ORDER_HEADERS_ALL.SOLD_TO_ORG_ID SOLD_TO_ORG_ID,
	MTL_MATERIAL_TRANSACTIONS.TRANSACTION_ID TRANSACTION_ID,
	MTL_MATERIAL_TRANSACTIONS.INVENTORY_ITEM_ID INVENTORY_ITEM_ID,
	OE_ORDER_HEADERS_ALL.PAYMENT_TERM_ID PAYMENT_TERM_ID,
	MTL_MATERIAL_TRANSACTIONS.PRIMARY_QUANTITY PRIMARY_QUANTITY,
	MTL_MATERIAL_TRANSACTIONS.ORGANIZATION_ID ORGANIZATION_ID,
	'SALES_ORDLNS~'||OE_ORDER_HEADERS_ALL.ORDER_CATEGORY_CODE||'~'||OE_ORDER_HEADERS_ALL.ORDER_TYPE_ID||'~'||DECODE(OE_ORDER_HEADERS_ALL.DROP_SHIP_FLAG,'Y','DROP SHIP','SELF SHIP') ORDER_TYPE_ID,
	OE_ORDER_HEADERS_ALL.ATTRIBUTE19 X_GENERIC_CUSTOMER_ID,
	OE_ORDER_LINES_ALL.SHIP_TO_ORG_ID X_SHIP_TO_ORG_ID,
	OE_ORDER_LINES_ALL.SOLD_TO_ORG_ID X_SOLD_TO_ORG_ID,
	OE_ORDER_LINES_ALL.SALESREP_ID X_SALESREP_ID,
	OE_ORDER_HEADERS_ALL.CUST_PO_NUMBER X_CUST_PO_NUMBER,
	(CASE WHEN OE_ORDER_HEADERS_ALL.ORDER_SOURCE_ID IS NOT NULL
THEN 'SALES_ORDSRC~'||TO_CHAR(OE_ORDER_HEADERS_ALL.ORDER_SOURCE_ID)
ELSE 
'0'
END) ORDER_SOURCE_ID
from	APPS.MTL_MATERIAL_TRANSACTIONS   MTL_MATERIAL_TRANSACTIONS, APPS.OE_ORDER_LINES_ALL   OE_ORDER_LINES_ALL, APPS.OE_ORDER_HEADERS_ALL   OE_ORDER_HEADERS_ALL
where	(1=1)
 And (MTL_MATERIAL_TRANSACTIONS.TRX_SOURCE_LINE_ID=OE_ORDER_LINES_ALL.LINE_ID)
AND (OE_ORDER_LINES_ALL.HEADER_ID=OE_ORDER_HEADERS_ALL.HEADER_ID)








)    SQ_XLA_CST ON SQ_XLA_TRANSACTION_ENTITIES.SOURCE_ID_INT_1=SQ_XLA_CST.TRANSACTION_ID AND SQ_XLA_AE_LINES_HEADER.SOURCE_DIST_TYPE_DL='MTL_TRANSACTION_ACCOUNTS'
where	(1=1)








