select	
	
	SQ_SUPPLIERS.SEGMENT1	   C1_SPLR_ACCT_NUM,
	SQ_SUPPLIERS.VENDOR_SITE_CODE	   C2_SPLR_ACCT_NAME,
	TO_CHAR(SQ_SUPPLIERS.ACCTS_PAY_CODE_COMBINATION_ID)	   C3_GL_RECNCL_ACCT_NUM,
	TO_CHAR(COALESCE(SQ_SUPPLIERS.TERMS_ID,SQ_SUPPLIERS.TERMS_ID1))	   C4_PAY_TERMS_CODE,
	COALESCE(COALESCE(SQ_SUPPLIERS.PAY_GROUP_LOOKUP_CODE,SQ_SUPPLIERS.PAY_GROUP_LOOKUP_CODE1),'__UNASSIGNED__')	   C5_PAYMENT_GRP_CODE,
	COALESCE(SQ_SUPPLIERS.PAY_ON_RECEIPT_SUMMARY_CODE,'__UNASSIGNED__')	   C6_SPLR_RECPT_TYPE_CODE,
	SQ_SUPPLIERS.ENABLED_FLAG	   C7_ACTIVE_FLG,
	TO_CHAR(SQ_SUPPLIERS.CREATED_BY)	   C8_CREATED_BY_ID,
	TO_CHAR(SQ_SUPPLIERS.LAST_UPDATED_BY)	   C9_CHANGED_BY_ID,
	SQ_SUPPLIERS.CREATION_DATE	   C10_CREATED_ON_DT,
	SQ_SUPPLIERS.LAST_UPDATE_DATE	   C11_CHANGED_ON_DT,
	SQ_SUPPLIERS.LAST_UPDATE_DATE1	   C12_AUX1_CHANGED_ON_DT,
	SQ_SUPPLIERS.LAST_UPDATE_DATE2	   C13_AUX2_CHANGED_ON_DT,
	SQ_SUPPLIERS.LAST_UPDATE_DATE3	   C14_AUX3_CHANGED_ON_DT,
	SQ_SUPPLIERS.DELETE_FLG	   C15_DELETE_FLG,
	SQ_SUPPLIERS.VENDOR_SITE_ID	   C16_INTEGRATION_ID,
	SQ_SUPPLIERS.X_CUSTOM	   C17_X_CUSTOM,
	SQ_SUPPLIERS.VENDOR_SITE_CODE	   C18_SUPPLIER_SITE_CODE,
	SQ_SUPPLIERS.ADDRESS_LINE1	   C19_ST_ADDRESS1,
	SQ_SUPPLIERS.ADDRESS_LINE2||'~'||SQ_SUPPLIERS.ADDRESS_LINE3	   C20_ST_ADDRESS2,
	COALESCE((CASE
WHEN RTRIM(TRIM(SQ_SUPPLIERS.CITY)) IS NULL THEN NULL
ELSE TRIM(SQ_SUPPLIERS.CITY)
END ),'#BIAPPS.ETL_UNSPEC_STR')	   C21_CITY_CODE,
	COALESCE((CASE
WHEN RTRIM(TRIM(SQ_SUPPLIERS.STATE)) IS NULL THEN NULL
ELSE TRIM(SQ_SUPPLIERS.STATE)
END ),'#BIAPPS.ETL_UNSPEC_STR')	   C22_STATE_PROV_CODE,
	COALESCE((CASE
WHEN RTRIM(TRIM(SQ_SUPPLIERS.COUNTRY)) IS NULL THEN NULL
ELSE TRIM(SQ_SUPPLIERS.COUNTRY)
END ),'#BIAPPS.ETL_UNSPEC_STR')	   C23_COUNTRY_REGION_CODE,
	COALESCE((CASE
WHEN RTRIM(TRIM(SQ_SUPPLIERS.PROVINCE)) IS NULL THEN NULL
ELSE TRIM(SQ_SUPPLIERS.PROVINCE)
END ),'#BIAPPS.ETL_UNSPEC_STR')	   C24_REGION_CODE,
	COALESCE((CASE
WHEN RTRIM(TRIM(SQ_SUPPLIERS.ZIP)) IS NULL THEN NULL
ELSE TRIM(SQ_SUPPLIERS.ZIP)
END ),'#BIAPPS.ETL_UNSPEC_STR')	   C25_POSTAL_CODE,
	SQ_SUPPLIERS.AREA_CODE||'-'||SQ_SUPPLIERS.PHONE	   C26_PHONE_NUM,
	SQ_SUPPLIERS.FAX_AREA_CODE||'-'||SQ_SUPPLIERS.FAX	   C27_FAX_NUM,
	SQ_SUPPLIERS.CUSTOMER_NUM	   C28_CUSTOMER_NUM,
	SQ_SUPPLIERS.VENDOR_ID	   C29_SUPPLIER_ID,
	SQ_SUPPLIERS.PARTY_ID	   C30_PARTY_ID,
	SQ_SUPPLIERS.PARTY_SITE_ID	   C31_PARTY_SITE_ID,
	SQ_SUPPLIERS.LOCATION_ID	   C32_LOCATION_ID,
	COALESCE(SQ_SUPPLIERS.PAYMENT_METHOD_CODE,'__UNASSIGNED__')	   C33_PYMNT_MTHD_LKP_CODE,
	SQ_SUPPLIERS.CITY	   C34_CITY,
	SQ_SUPPLIERS.COUNTRY	   C35_COUNTRY,
	SQ_SUPPLIERS.STATE	   C36_STATE,
	SQ_SUPPLIERS.PROVINCE	   C37_PROVINCE
from	
( /* Subselect from SDE_ORA_SupplierAccountDimension.W_SUPPLIER_ACCOUNT_DS_SQ_SUPPLIERS
*/
select 
	   S.SEGMENT1 SEGMENT1,
	S.VENDOR_NAME VENDOR_NAME,
	SSA.ACCTS_PAY_CODE_COMBINATION_ID ACCTS_PAY_CODE_COMBINATION_ID,
	S.TERMS_ID TERMS_ID1,
	SSA.TERMS_ID TERMS_ID,
	SSA.PAY_GROUP_LOOKUP_CODE PAY_GROUP_LOOKUP_CODE,
	SSA.PAY_ON_RECEIPT_SUMMARY_CODE PAY_ON_RECEIPT_SUMMARY_CODE,
	S.ENABLED_FLAG ENABLED_FLAG,
	SSA.CREATED_BY CREATED_BY,
	SSA.LAST_UPDATED_BY LAST_UPDATED_BY,
	SSA.CREATION_DATE CREATION_DATE,
SSA.LAST_UPDATE_DATE
 LAST_UPDATE_DATE,
	SSA.VENDOR_SITE_ID VENDOR_SITE_ID,
	SSA.VENDOR_SITE_CODE VENDOR_SITE_CODE,
	SSA.ADDRESS_LINE1 ADDRESS_LINE1,
	SSA.ADDRESS_LINE2 ADDRESS_LINE2,
	SSA.ADDRESS_LINE3 ADDRESS_LINE3,
	SSA.CITY CITY,
	SSA.STATE STATE,
	SSA.COUNTRY COUNTRY,
	SSA.PROVINCE PROVINCE,
	SSA.ZIP ZIP,
	SSA.AREA_CODE AREA_CODE,
	SSA.PHONE PHONE,
	SSA.FAX_AREA_CODE FAX_AREA_CODE,
	SSA.FAX FAX,
	SSA.CUSTOMER_NUM CUSTOMER_NUM,
	SSA.VENDOR_ID VENDOR_ID,
	S.PARTY_ID PARTY_ID,
	SSA.PARTY_SITE_ID PARTY_SITE_ID,
	SSA.LOCATION_ID LOCATION_ID,
	S.LAST_UPDATE_DATE LAST_UPDATE_DATE1,
	S.PAY_GROUP_LOOKUP_CODE PAY_GROUP_LOOKUP_CODE1,
	'0' X_CUSTOM,
	
'N'
 DELETE_FLG,
	MAX(IBYPMNT.PAYMENT_METHOD_CODE) PAYMENT_METHOD_CODE,
	MAX(IBYPMNT.LAST_UPDATE_DATE) LAST_UPDATE_DATE2,
	MAX(IBYPAYEE.LAST_UPDATE_DATE) LAST_UPDATE_DATE3
from	((APPS.AP_SUPPLIERS    S INNER JOIN APPS.AP_SUPPLIER_SITES_ALL    SSA ON S.VENDOR_ID=SSA.VENDOR_ID) LEFT OUTER JOIN APPS.IBY_EXTERNAL_PAYEES_ALL    IBYPAYEE ON SSA.VENDOR_SITE_ID=IBYPAYEE.SUPPLIER_SITE_ID) LEFT OUTER JOIN APPS.IBY_EXT_PARTY_PMT_MTHDS    IBYPMNT ON IBYPAYEE.EXT_PAYEE_ID = IBYPMNT.EXT_PMT_PARTY_ID
AND 'Y' = IBYPMNT.PRIMARY_FLAG
where	(1=1)

And (


(S.LAST_UPDATE_DATE>TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS') 
OR SSA.LAST_UPDATE_DATE>TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS')
OR IBYPMNT.LAST_UPDATE_DATE>TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS')
OR IBYPAYEE.LAST_UPDATE_DATE>TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS'))


)
 And (NOT IBYPAYEE.SUPPLIER_SITE_ID IS NULL 
AND IBYPAYEE.PAYMENT_FUNCTION='PAYABLES_DISB')
Group By S.SEGMENT1,
 S.VENDOR_NAME,
 SSA.ACCTS_PAY_CODE_COMBINATION_ID,
 S.TERMS_ID,
 SSA.TERMS_ID,
 SSA.PAY_GROUP_LOOKUP_CODE,
 SSA.PAY_ON_RECEIPT_SUMMARY_CODE,
 S.ENABLED_FLAG,
 SSA.CREATED_BY,
 SSA.LAST_UPDATED_BY,
 SSA.CREATION_DATE,
 
SSA.LAST_UPDATE_DATE
,
 SSA.VENDOR_SITE_ID,
 SSA.VENDOR_SITE_CODE,
 SSA.ADDRESS_LINE1,
 SSA.ADDRESS_LINE2,
 SSA.ADDRESS_LINE3,
 SSA.CITY,
 SSA.STATE,
 SSA.COUNTRY,
 SSA.PROVINCE,
 SSA.ZIP,
 SSA.AREA_CODE,
 SSA.PHONE,
 SSA.FAX_AREA_CODE,
 SSA.FAX,
 SSA.CUSTOMER_NUM,
 SSA.VENDOR_ID,
 S.PARTY_ID,
 SSA.PARTY_SITE_ID,
 SSA.LOCATION_ID,
 S.LAST_UPDATE_DATE,
 S.PAY_GROUP_LOOKUP_CODE,
 
'N'
)   SQ_SUPPLIERS
where	(1=1)








